import AppKit
import SwiftUI

/// Loads the two menu bar glyph variants (see Scripts/generate-icons.sh for
/// how they're produced) and hands back a SwiftUI `Image` for the
/// MenuBarExtra label.
///
/// Both variants are "template" images: solid black shape + alpha channel,
/// no color. Setting `isTemplate = true` tells AppKit to treat the black
/// pixels as a stencil and recolor them automatically to match the current
/// menu bar appearance (dark text in light mode, light in dark mode, and
/// the dimmed/highlighted tinting when the item is clicked) — exactly how
/// Wi-Fi, Bluetooth, and Battery status icons behave. If you ever replace
/// these PNGs, keep them pure black + alpha; any other color baked in will
/// look wrong once isTemplate does its recoloring.
enum MenuBarIconProvider {

    /// Experiment: bright-green background + black glyph, full color,
    /// instead of the HIG-standard monochrome template icon below. Flip
    /// back to `true` and rebuild the app bundle to revert instantly — the
    /// monochrome PNGs are untouched and still generated by
    /// Scripts/generate-icons.sh regardless of which way this is set, so
    /// reverting needs no file changes, just this one line.
    private static let useMonochromeTemplateIcon = false

    /// Per the plan: only two persistent glyphs exist. "On" (filled) is
    /// shown only when the agent is confidently running; every other state
    /// — stopped, starting, stopping, unknown, not installed — uses "Off"
    /// (dimmed). All the finer-grained detail lives in the dropdown itself,
    /// not in the persistent menu bar glyph.
    static func image(for status: AgentStatus) -> Image {
        let isRunning: Bool
        if case .running = status {
            isRunning = true
        } else {
            isRunning = false
        }

        if useMonochromeTemplateIcon {
            let baseName = isRunning ? "MenuBarIcon-On" : "MenuBarIcon-Off"
            return Image(nsImage: loadImage(baseName: baseName, isTemplate: true))
        } else {
            let baseName = isRunning ? "MenuBarIcon-On-Color" : "MenuBarIcon-Off-Color"
            return Image(nsImage: loadImage(baseName: baseName, isTemplate: false))
        }
    }

    private static func loadImage(baseName: String, isTemplate: Bool) -> NSImage {
        let image = NSImage(size: NSSize(width: 18, height: 18))

        if let rep1x = loadRepresentation(named: baseName) {
            image.addRepresentation(rep1x)
        }
        if let rep2x = loadRepresentation(named: "\(baseName)@2x") {
            image.addRepresentation(rep2x)
        }

        image.isTemplate = isTemplate
        return image
    }

    /// Looks up one PNG by two different routes, in order:
    ///
    /// 1. `Bundle.main`'s standard `Contents/Resources/MenuBarIcon/` — this
    ///    is where Scripts/build-app-bundle.sh copies the PNGs directly
    ///    (plain files, no SPM `.bundle` wrapper) when assembling the real
    ///    .app. This is the path used once you're running the packaged app.
    ///
    /// 2. `Bundle.module` (SPM's auto-generated resource bundle) — this is
    ///    what makes `swift run`/`swift build` work during development,
    ///    where there's no real .app bundle for (1) to find anything in.
    ///
    /// Why not just always use Bundle.module? Its generated accessor
    /// requires the resource bundle to sit at the *top level* of the .app
    /// (see .build/*/resource_bundle_accessor.swift), which `codesign`
    /// refuses to seal ("unsealed contents present in the bundle root") —
    /// that combination is exactly what made the packaged app crash
    /// instantly and silently on double-click before this fix. Preferring
    /// the standard Contents/Resources location for the shipped app avoids
    /// that entirely, while still keeping the SPM path for local dev.
    private static func loadRepresentation(named name: String) -> NSImageRep? {
        if let url = Bundle.main.url(forResource: name, withExtension: "png", subdirectory: "MenuBarIcon"),
           let rep = NSImage(contentsOf: url)?.representations.first {
            return rep
        }
        if let url = Bundle.module.url(forResource: name, withExtension: "png", subdirectory: "MenuBarIcon"),
           let rep = NSImage(contentsOf: url)?.representations.first {
            return rep
        }
        return nil
    }
}
